const lastName = '山田';
const firstName = '太郎';
const fullName = lastName + '　' + firstName;
const myAge = 15;
const friendAge = 17;
const totalAge = myAge + friendAge;
const numberifDays = totalAge * 365;
const numberOfChildren = 3;
const numberOfCakes = 10;
const numberOfCakesByChild = numberOfCakes / numberOfChildren;
const numberOfRestOfCakes = numberOfCakes % numberOfChildren;
console.log (lastName);
console.log (firstName);
console.log (fullName);
console.log (myAge);
console.log (friendAge);
console.log (totalAge);
console.log (numberifDays);
console.log (numberOfChildren);
console.log (numberOfCakes);
console.log (numberOfCakesByChild);
console.log (numberOfRestOfCakes);